[package]
name = "schema-validator"
version = "0.2.0"
edition = "2021"
authors = ["Laszlo Solova <laszlo@solova.com>"]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
async-trait = "0.1.89"
jsonschema = { version = "0.40.0", default-features = false, features = ["resolve-async"] }
regex = "1.12.2"
reqwest = { version = "0.13.1", features = ['json'] }
serde_json = "1.0.149"
wasm-bindgen = "0.2.108"
wasm-bindgen-futures = "0.4.58"

# serde = { version = "1.0.228", features = ["derive"] }
# serde-wasm-bindgen = "0.6.5"
# web-sys = { version = "0.3.83", features = ['Headers', 'Request', 'RequestInit', 'RequestMode', 'Response', 'Window'] }

[dev-dependencies]
tokio = { version = "1.41.1", features = ["full"] }
